# Generated by Django 6.0 on 2026-01-05 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Job title/position', max_length=255)),
                ('company', models.CharField(blank=True, help_text='Company name', max_length=255)),
                ('description', models.TextField(help_text='Full job description')),
                ('required_skills', models.TextField(blank=True, help_text='Required skills (comma-separated or newline-separated)')),
                ('experience_level', models.CharField(blank=True, choices=[('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior Level'), ('executive', 'Executive')], default='mid', max_length=50)),
                ('location', models.CharField(blank=True, help_text='Job location', max_length=255)),
                ('salary_range', models.CharField(blank=True, help_text='Salary range', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.ForeignKey(blank=True, help_text='Associated resume (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_descriptions', to='resumes.resume')),
            ],
            options={
                'verbose_name': 'Job Description',
                'verbose_name_plural': 'Job Descriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
