# Generated by Django 6.0 on 2026-01-05 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Created'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='created', max_length=20)),
                ('title', models.CharField(blank=True, help_text='Interview title (auto-generated if not provided)', max_length=255)),
                ('current_question_index', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_description', models.ForeignKey(blank=True, help_text='Associated job description', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews', to='interviews.jobdescription')),
                ('resume', models.ForeignKey(blank=True, help_text='Associated resume', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews', to='resumes.resume')),
            ],
            options={
                'verbose_name': 'Interview',
                'verbose_name_plural': 'Interviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
