# Generated by Django 6.0 on 2026-01-05 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_interview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='The interview question')),
                ('question_type', models.CharField(choices=[('technical', 'Technical'), ('behavioral', 'Behavioral'), ('situational', 'Situational'), ('general', 'General')], default='general', help_text='Type of question', max_length=50)),
                ('order_index', models.PositiveIntegerField(default=0, help_text='Order of question in the interview')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', help_text='Difficulty level', max_length=20)),
                ('generated_by_ai', models.BooleanField(default=True)),
                ('ai_model', models.CharField(blank=True, help_text='AI model used to generate question', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interview', models.ForeignKey(help_text='Associated interview session', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interviews.interview')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['interview', 'order_index'],
                'unique_together': {('interview', 'order_index')},
            },
        ),
    ]
