# Generated by Django 6.0 on 2026-01-05 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, help_text='Transcribed text answer', null=True)),
                ('audio_file', models.FileField(blank=True, help_text='Audio recording of the answer', null=True, upload_to='answers/audio/%Y/%m/%d/')),
                ('score', models.FloatField(default=0.0, help_text='Score out of 10')),
                ('evaluation', models.TextField(blank=True, help_text='AI evaluation of the answer')),
                ('strengths', models.TextField(blank=True, help_text='Identified strengths in the answer')),
                ('improvements', models.TextField(blank=True, help_text='Suggested improvements')),
                ('duration_seconds', models.FloatField(blank=True, help_text='Duration of answer in seconds', null=True)),
                ('transcribed', models.BooleanField(default=False, help_text='Whether audio has been transcribed')),
                ('evaluated', models.BooleanField(default=False, help_text='Whether answer has been evaluated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interview', models.ForeignKey(help_text='Associated interview session', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='interviews.interview')),
                ('question', models.ForeignKey(help_text='The question being answered', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='interviews.question')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'ordering': ['interview', 'question__order_index'],
            },
        ),
        migrations.CreateModel(
            name='InterviewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField(default=0.0, help_text='Overall interview score out of 10')),
                ('technical_score', models.FloatField(default=0.0, help_text='Technical questions score')),
                ('behavioral_score', models.FloatField(default=0.0, help_text='Behavioral questions score')),
                ('communication_score', models.FloatField(default=0.0, help_text='Communication score')),
                ('summary', models.TextField(help_text='Overall interview summary')),
                ('strengths', models.TextField(help_text='Overall strengths identified')),
                ('areas_for_improvement', models.TextField(help_text='Areas that need improvement')),
                ('recommendations', models.TextField(help_text='Recommendations for the candidate')),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('questions_answered', models.PositiveIntegerField(default=0)),
                ('average_answer_length', models.FloatField(default=0.0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interview', models.OneToOneField(help_text='Associated interview session', on_delete=django.db.models.deletion.CASCADE, related_name='report', to='interviews.interview')),
            ],
            options={
                'verbose_name': 'Interview Report',
                'verbose_name_plural': 'Interview Reports',
                'ordering': ['-generated_at'],
            },
        ),
    ]
