# Generated by Django 6.0 on 2026-01-05 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_answer_interviewreport'),
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATSMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.DecimalField(decimal_places=2, help_text='Overall ATS match score (0-100)', max_digits=5)),
                ('skills_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Skills match score (0-100)', max_digits=5)),
                ('experience_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Experience match score (0-100)', max_digits=5)),
                ('education_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Education match score (0-100)', max_digits=5)),
                ('match_analysis', models.TextField(blank=True, help_text='Detailed AI analysis of the match')),
                ('strengths', models.TextField(blank=True, help_text='Key strengths identified')),
                ('gaps', models.TextField(blank=True, help_text='Gaps or missing requirements')),
                ('recommendations', models.TextField(blank=True, help_text='Recommendations for improvement')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('reviewed', 'Reviewed'), ('rejected', 'Rejected')], default='matched', help_text='Match status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched_at', models.DateTimeField(auto_now_add=True, help_text='When the match was created')),
                ('job_description', models.ForeignKey(help_text='Job description being matched', on_delete=django.db.models.deletion.CASCADE, related_name='ats_matches', to='interviews.jobdescription')),
                ('resume', models.ForeignKey(help_text='Resume being matched', on_delete=django.db.models.deletion.CASCADE, related_name='ats_matches', to='resumes.resume')),
            ],
            options={
                'verbose_name': 'ATS Match',
                'verbose_name_plural': 'ATS Matches',
                'ordering': ['-overall_score', '-created_at'],
                'unique_together': {('job_description', 'resume')},
            },
        ),
    ]
