# Generated by Django 6.0 on 2026-01-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0005_atsmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(blank=True, help_text='Whether the MCQ answer is correct (null if not MCQ)', null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='selected_option',
            field=models.CharField(blank=True, help_text='Selected MCQ option (A, B, C, D, etc.)', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, help_text='Correct answer option (A, B, C, D, etc.)', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='is_mcq',
            field=models.BooleanField(default=False, help_text='Whether this is an MCQ question'),
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text='MCQ options (list of strings)'),
        ),
    ]
