# Generated by Django 6.0 on 2026-01-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0006_answer_is_correct_answer_selected_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Time limit for the interview in minutes'),
        ),
        migrations.AddField(
            model_name='question',
            name='skill_tags',
            field=models.JSONField(blank=True, default=list, help_text='List of skills this question tests (extracted from required_skills)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, help_text='Correct answer option (A, B, C, D) for MCQ questions', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_mcq',
            field=models.BooleanField(default=True, help_text='Whether this is an MCQ question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text='MCQ options (list of strings, 4 options for MCQ)', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('technical', 'Technical'), ('behavioral', 'Behavioral'), ('situational', 'Situational'), ('general', 'General'), ('coding', 'Coding/Programming')], default='general', help_text='Type of question', max_length=50),
        ),
    ]
